server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
spring:
  thymeleaf.cache: false
  mvc:
    static-path-pattern: /**
  servlet.multipart:
      max-request-size: 30MB
      max-file-size: 30MB
logging.level:
  org.springframework: error
  org.apache.shiro: error
  org.hibernate.SQL: error
  com.lcw.one: debug

# Rest API前缀地址
restPath: /api

# App信息
one:
  application:
    name: One Admin System
    shortName: One
    version: V1.2
    powerByName: lcw2004
    powerByLink: https://github.com/lcw2004
  file:
    type: local
    temp: D:\Files\temp
    local:
      path: D:\Files
    oss:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: test
      accessKeySecret: test
      bucketName: dev
    local-oss:
      max-time: 7
  url: http://localhost:9000
  weixin:
    appId: wxa5b74cf00bb65181
    appSecret: e105d543814851868a8e90c849bb0d82

#=============================#
#===== Database Settings =====#
#=============================#
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/one?useUnicode=true&characterEncoding=utf-8
  username: root
  password: one
  driver-class-name: com.mysql.jdbc.Driver
  druid:
    initial-size: 3
    max-active: 5
    min-idle: 2
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x' FROM DUAL
spring.jpa.properties.hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    hql.bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsOrClauseBulkIdStrategy

#=============================#
#=====   Email Settings  =====#
#=============================#
mail:
  protocol: smtp
  host: smtp.qq.com
  port: 465
  smtp:
    socketFactory.port: 465
    auth: true
    starttls.enable: true
    debug: true
    starttls.required: true
    socketFactory.fallback: false
  from:
    mail: test@qq.com
    name: test
  username: test@qq.com
  password: test

#=============================#
#=====   Redis Settings  =====#
#=============================#
spring.redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  lettuce.pool:
    max-active: 8
    max-wait: -1ms
    max-idle: 8
    min-idle: 0